# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monica Johnson, Psy.D.
job: Clinical Psychologist
email: info@monicajohnson.org
description: Dr. Monica Johnson, Psy.D.  Psychologist specializing in DBT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://monicajohnson.org/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [/bower_components/]

sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  # style: compressed